//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM_tecnicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class hv
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public System.DateTime fi { get; set; }
        public string trabajo { get; set; }
        public System.DateTime ff { get; set; }
        public string mante { get; set; }
        public string operario { get; set; }
        public string insumos { get; set; }
        public string observa { get; set; }
    }
}
