//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM_tecnicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int id { get; set; }
        public string empresa { get; set; }
        public string edificio { get; set; }
        public string area { get; set; }
        public string local { get; set; }
        public string fechaini { get; set; }
        public string fechafi { get; set; }
        public string descripcion { get; set; }
        public string Necco { get; set; }
        public string recursos { get; set; }
        public string prioridad { get; set; }
        public string mto { get; set; }
        public string nombre_t { get; set; }
        public string material { get; set; }
        public string cantida { get; set; }
        public Nullable<long> Pu { get; set; }
        public Nullable<long> importe { get; set; }
        public string duracion { get; set; }
        public Nullable<long> costohh { get; set; }
        public Nullable<long> importeHH { get; set; }
        public string indicadores { get; set; }
        public string observaciones { get; set; }
        public string evaluacion { get; set; }
        public string causa { get; set; }
        public string recibido { get; set; }
    }
}
