//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM_tecnicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string fabricante { get; set; }
        public string seccion { get; set; }
        public string alto { get; set; }
        public string ancho { get; set; }
        public string largo { get; set; }
        public string color { get; set; }
        public string medios { get; set; }
        public string voltaje { get; set; }
        public string corriente { get; set; }
        public string potencia { get; set; }
        public string funcion { get; set; }
        public string ph { get; set; }
    }
}
